<?php 
NAMESPACE \HTML\ELEMENT\BODY;
CLASS IMG EXTENDS \HTML\ELEMENT\BODY\INDEX {
  PUBLIC $SRC;
  PUBLIC $WIDTH;
  PUBLIC $HEIGHT;
  PUBLIC function IMG(){?><IMG <?php parent::ATTRIBUTES();?> /><?php }
}?>
